#pragma once

#include "NativeGameplayTags.h"

namespace SL_GameplayTags
{
	/** Input Tags **/
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipKatana);
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipKatana);
	
	/** Player Tags **/
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Katana);
	
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Katana);
	SWORD_LEGACY_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Katana);
}